### PR TITLE
fix: active routes or stops may not appear to the user

### LINKED ISSUE #266: Active markers and routes sometimes don't appear to the user
This could be because they're drawn Under the other routes/stops, and so not visible.

### PR DESCRIPTION
**Pull request by jxjj**
This fixes an issue were active routes or stops may not appear to the user. 

Draw order matters, so stops/routes that are drawn later will appear on top of earlier routes. If an inactive stop has the same (or similar) location to the active stop, the active stop may be rendered "under" the inactive stop marker, effectively hiding the active stop. 

This changes tour map draw order so that inactive routes and stops are drawn before active routes and stops. Also, the stop preceding the active stop is drawn later so that it appears on the map (as it's start point for the active stop route).

Closes #266

### CODE REVIEW

File: resources/camino-trekker/components/MapMarkerLabel/MapMarkerLabel.vue [hunk 1]
```diff
@@ -13,9 +13,11 @@
   </div>
 </template>
 <script setup lang="ts">
+export type MapMarkerLabelColors = "pink" | "orange" | "default";
+
 withDefaults(
   defineProps<{
-    color?: "pink" | "orange" | "default";
+    color?: MapMarkerLabelColors;
```
Comment (cmcfadden) [inline resources/camino-trekker/components/MapMarkerLabel/MapMarkerLabel.vue:20]: I think you might be addicted to typescript 😂

**Review by cmcfadden — APPROVED** [review]
Looks good!

File: resources/camino-trekker/components/MapMarkerLabel/MapMarkerLabel.vue (hunk 1 above)
Comment (jxjj) [reply resources/camino-trekker/components/MapMarkerLabel/MapMarkerLabel.vue:20]: Totally – the autocompletion is addictive. 

Also, I don't think exporting types works from vue files, so I need to remove this.
